<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<!-- NewPage -->
<html lang="en">
<head>
<!-- Generated by javadoc -->
<title>UserApi (Spotify App Remote)</title>
<link rel="stylesheet" type="text/css" href="../../../../../stylesheet.css" title="Style">
<script type="text/javascript" src="../../../../../script.js"></script>
</head>
<body>
<script type="text/javascript"><!--
    try {
        if (location.href.indexOf('is-external=true') == -1) {
            parent.document.title="UserApi (Spotify App Remote)";
        }
    }
    catch(err) {
    }
//-->
var methods = {"i0":6,"i1":6,"i2":6,"i3":6,"i4":6,"i5":6};
var tabs = {65535:["t0","All Methods"],2:["t2","Instance Methods"],4:["t3","Abstract Methods"]};
var altColor = "altColor";
var rowColor = "rowColor";
var tableTab = "tableTab";
var activeTableTab = "activeTableTab";
</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
<!-- ========= START OF TOP NAVBAR ======= -->
<div class="topNav"><a name="navbar.top">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.top" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.top.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../../../overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../../../index-all.html">Index</a></li>
<li><a href="../../../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../../../com/spotify/android/appremote/api/SpotifyAppRemote.html" title="class in com.spotify.android.appremote.api"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li>Next&nbsp;Class</li>
</ul>
<ul class="navList">
<li><a href="../../../../../index.html?com/spotify/android/appremote/api/UserApi.html" target="_top">Frames</a></li>
<li><a href="UserApi.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_top">
<li><a href="../../../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_top");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.top">
<!--   -->
</a></div>
<!-- ========= END OF TOP NAVBAR ========= -->
<!-- ======== START OF CLASS DATA ======== -->
<div class="header">
<div class="subTitle">com.spotify.android.appremote.api</div>
<h2 title="Interface UserApi" class="title">Interface UserApi</h2>
</div>
<div class="contentContainer">
<div class="description">
<ul class="blockList">
<li class="blockList">
<hr>
<br>
<pre>public interface <span class="typeNameLabel">UserApi</span></pre>
<div class="block">Get user-related data and perform actions related to current user Get an instance of an UserApi
 with <a href="../../../../../com/spotify/android/appremote/api/SpotifyAppRemote.html#getUserApi--"><code>SpotifyAppRemote.getUserApi()</code></a>.</div>
<dl>
<dt><span class="seeLabel">See Also:</span></dt>
<dd><a href="../../../../../com/spotify/android/appremote/api/SpotifyAppRemote.html" title="class in com.spotify.android.appremote.api"><code>SpotifyAppRemote</code></a></dd>
</dl>
</li>
</ul>
</div>
<div class="summary">
<ul class="blockList">
<li class="blockList">
<!-- ========== METHOD SUMMARY =========== -->
<ul class="blockList">
<li class="blockList"><a name="method.summary">
<!--   -->
</a>
<h3>Method Summary</h3>
<table class="memberSummary" border="0" cellpadding="3" cellspacing="0" summary="Method Summary table, listing methods, and an explanation">
<caption><span id="t0" class="activeTableTab"><span>All Methods</span><span class="tabEnd">&nbsp;</span></span><span id="t2" class="tableTab"><span><a href="javascript:show(2);">Instance Methods</a></span><span class="tabEnd">&nbsp;</span></span><span id="t3" class="tableTab"><span><a href="javascript:show(4);">Abstract Methods</a></span><span class="tabEnd">&nbsp;</span></span></caption>
<tr>
<th class="colFirst" scope="col">Modifier and Type</th>
<th class="colLast" scope="col">Method and Description</th>
</tr>
<tr id="i0" class="altColor">
<td class="colFirst"><code><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/Empty.html" title="class in com.spotify.protocol.types">Empty</a>&gt;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../../com/spotify/android/appremote/api/UserApi.html#addToLibrary-java.lang.String-">addToLibrary</a></span>(java.lang.String&nbsp;uri)</code>
<div class="block">Adds item to users' library.</div>
</td>
</tr>
<tr id="i1" class="rowColor">
<td class="colFirst"><code><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types">Capabilities</a>&gt;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../../com/spotify/android/appremote/api/UserApi.html#getCapabilities--">getCapabilities</a></span>()</code>
<div class="block">Get the <a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types"><code>Capabilities</code></a> of a current user.</div>
</td>
</tr>
<tr id="i2" class="altColor">
<td class="colFirst"><code><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/LibraryState.html" title="class in com.spotify.protocol.types">LibraryState</a>&gt;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../../com/spotify/android/appremote/api/UserApi.html#getLibraryState-java.lang.String-">getLibraryState</a></span>(java.lang.String&nbsp;uri)</code>
<div class="block">Gets library state for the given Spotify uri.</div>
</td>
</tr>
<tr id="i3" class="rowColor">
<td class="colFirst"><code><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/Empty.html" title="class in com.spotify.protocol.types">Empty</a>&gt;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../../com/spotify/android/appremote/api/UserApi.html#removeFromLibrary-java.lang.String-">removeFromLibrary</a></span>(java.lang.String&nbsp;uri)</code>
<div class="block">Removes item from users library.</div>
</td>
</tr>
<tr id="i4" class="altColor">
<td class="colFirst"><code><a href="../../../../../com/spotify/protocol/client/Subscription.html" title="class in com.spotify.protocol.client">Subscription</a>&lt;<a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types">Capabilities</a>&gt;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../../com/spotify/android/appremote/api/UserApi.html#subscribeToCapabilities--">subscribeToCapabilities</a></span>()</code>
<div class="block">Same as <a href="../../../../../com/spotify/android/appremote/api/UserApi.html#getCapabilities--"><code>getCapabilities()</code></a>, but subscription.</div>
</td>
</tr>
<tr id="i5" class="rowColor">
<td class="colFirst"><code><a href="../../../../../com/spotify/protocol/client/Subscription.html" title="class in com.spotify.protocol.client">Subscription</a>&lt;<a href="../../../../../com/spotify/protocol/types/UserStatus.html" title="class in com.spotify.protocol.types">UserStatus</a>&gt;</code></td>
<td class="colLast"><code><span class="memberNameLink"><a href="../../../../../com/spotify/android/appremote/api/UserApi.html#subscribeToUserStatus--">subscribeToUserStatus</a></span>()</code>&nbsp;</td>
</tr>
</table>
</li>
</ul>
</li>
</ul>
</div>
<div class="details">
<ul class="blockList">
<li class="blockList">
<!-- ============ METHOD DETAIL ========== -->
<ul class="blockList">
<li class="blockList"><a name="method.detail">
<!--   -->
</a>
<h3>Method Detail</h3>
<a name="getCapabilities--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>getCapabilities</h4>
<pre><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types">Capabilities</a>&gt;&nbsp;getCapabilities()</pre>
<div class="block">Get the <a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types"><code>Capabilities</code></a> of a current user. It is useful to call before you make call to
 <a href="../../../../../com/spotify/android/appremote/api/PlayerApi.html#play-java.lang.String-"><code>PlayerApi.play(String)</code></a>:

 <pre>
 <code> userApi.getCapabilities()
    .setResultCallback( capabilities -&gt;
      if (capabilities.canPlayOnDemand) {
          playerApi.play(trackUri);
      } else {
          // current user is not able to play on demand
      }
 )
 </code>
 </pre>

 Introduced in <code>com.spotify.protocol.client.RequiredFeatures#FEATURES_V1</code></div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client"><code>CallResult</code></a> with <a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types"><code>Capabilities</code></a> of a current user</dd>
</dl>
</li>
</ul>
<a name="subscribeToCapabilities--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>subscribeToCapabilities</h4>
<pre><a href="../../../../../com/spotify/protocol/client/Subscription.html" title="class in com.spotify.protocol.client">Subscription</a>&lt;<a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types">Capabilities</a>&gt;&nbsp;subscribeToCapabilities()</pre>
<div class="block">Same as <a href="../../../../../com/spotify/android/appremote/api/UserApi.html#getCapabilities--"><code>getCapabilities()</code></a>, but subscription. Introduced in <code>com.spotify.protocol.client.RequiredFeatures#FEATURES_V1</code></div>
<dl>
<dt><span class="returnLabel">Returns:</span></dt>
<dd><a href="../../../../../com/spotify/protocol/client/Subscription.html" title="class in com.spotify.protocol.client"><code>Subscription</code></a> to <a href="../../../../../com/spotify/protocol/types/Capabilities.html" title="class in com.spotify.protocol.types"><code>Capabilities</code></a> of a current user</dd>
</dl>
</li>
</ul>
<a name="subscribeToUserStatus--">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>subscribeToUserStatus</h4>
<pre><a href="../../../../../com/spotify/protocol/client/Subscription.html" title="class in com.spotify.protocol.client">Subscription</a>&lt;<a href="../../../../../com/spotify/protocol/types/UserStatus.html" title="class in com.spotify.protocol.types">UserStatus</a>&gt;&nbsp;subscribeToUserStatus()</pre>
</li>
</ul>
<a name="addToLibrary-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>addToLibrary</h4>
<pre><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/Empty.html" title="class in com.spotify.protocol.types">Empty</a>&gt;&nbsp;addToLibrary(java.lang.String&nbsp;uri)</pre>
<div class="block">Adds item to users' library. Supported uris currently include: Track - example:
 spotify:track:6rqhFgbbKwnb9MLmUQDhG6 Album - example: spotify:album:2VYSDvc0ZdcfkXDcYVjHs6
 Introduced in <code>com.spotify.protocol.client.RequiredFeatures#FEATURES_V1</code></div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>uri</code> - to get saved state for</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>a pending call result that can be used to track the success/failure of this command</dd>
</dl>
</li>
</ul>
<a name="removeFromLibrary-java.lang.String-">
<!--   -->
</a>
<ul class="blockList">
<li class="blockList">
<h4>removeFromLibrary</h4>
<pre><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/Empty.html" title="class in com.spotify.protocol.types">Empty</a>&gt;&nbsp;removeFromLibrary(java.lang.String&nbsp;uri)</pre>
<div class="block">Removes item from users library. Supported uris currently include: Track - example:
 spotify:track:6rqhFgbbKwnb9MLmUQDhG6 Album - example: spotify:album:2VYSDvc0ZdcfkXDcYVjHs6
 Introduced in <code>com.spotify.protocol.client.RequiredFeatures#FEATURES_V1</code></div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>uri</code> - to get saved state for</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>a pending call result that can be used to track the success/failure of this command</dd>
</dl>
</li>
</ul>
<a name="getLibraryState-java.lang.String-">
<!--   -->
</a>
<ul class="blockListLast">
<li class="blockList">
<h4>getLibraryState</h4>
<pre><a href="../../../../../com/spotify/protocol/client/CallResult.html" title="class in com.spotify.protocol.client">CallResult</a>&lt;<a href="../../../../../com/spotify/protocol/types/LibraryState.html" title="class in com.spotify.protocol.types">LibraryState</a>&gt;&nbsp;getLibraryState(java.lang.String&nbsp;uri)</pre>
<div class="block">Gets library state for the given Spotify uri. Supported uris currently include: Track -
 example: spotify:track:6rqhFgbbKwnb9MLmUQDhG6 Album - example:
 spotify:album:2VYSDvc0ZdcfkXDcYVjHs6 Introduced in <code>com.spotify.protocol.client.RequiredFeatures#FEATURES_V1</code></div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>uri</code> - track or album to get library state for</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd><a href="../../../../../com/spotify/protocol/types/LibraryState.html" title="class in com.spotify.protocol.types"><code>LibraryState</code></a> of a given uri.</dd>
</dl>
</li>
</ul>
</li>
</ul>
</li>
</ul>
</div>
</div>
<!-- ========= END OF CLASS DATA ========= -->
<!-- ======= START OF BOTTOM NAVBAR ====== -->
<div class="bottomNav"><a name="navbar.bottom">
<!--   -->
</a>
<div class="skipNav"><a href="#skip.navbar.bottom" title="Skip navigation links">Skip navigation links</a></div>
<a name="navbar.bottom.firstrow">
<!--   -->
</a>
<ul class="navList" title="Navigation">
<li><a href="../../../../../overview-summary.html">Overview</a></li>
<li><a href="package-summary.html">Package</a></li>
<li class="navBarCell1Rev">Class</li>
<li><a href="package-tree.html">Tree</a></li>
<li><a href="../../../../../deprecated-list.html">Deprecated</a></li>
<li><a href="../../../../../index-all.html">Index</a></li>
<li><a href="../../../../../help-doc.html">Help</a></li>
</ul>
</div>
<div class="subNav">
<ul class="navList">
<li><a href="../../../../../com/spotify/android/appremote/api/SpotifyAppRemote.html" title="class in com.spotify.android.appremote.api"><span class="typeNameLink">Prev&nbsp;Class</span></a></li>
<li>Next&nbsp;Class</li>
</ul>
<ul class="navList">
<li><a href="../../../../../index.html?com/spotify/android/appremote/api/UserApi.html" target="_top">Frames</a></li>
<li><a href="UserApi.html" target="_top">No&nbsp;Frames</a></li>
</ul>
<ul class="navList" id="allclasses_navbar_bottom">
<li><a href="../../../../../allclasses-noframe.html">All&nbsp;Classes</a></li>
</ul>
<div>
<script type="text/javascript"><!--
  allClassesLink = document.getElementById("allclasses_navbar_bottom");
  if(window==top) {
    allClassesLink.style.display = "block";
  }
  else {
    allClassesLink.style.display = "none";
  }
  //-->
</script>
</div>
<div>
<ul class="subNavList">
<li>Summary:&nbsp;</li>
<li>Nested&nbsp;|&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.summary">Method</a></li>
</ul>
<ul class="subNavList">
<li>Detail:&nbsp;</li>
<li>Field&nbsp;|&nbsp;</li>
<li>Constr&nbsp;|&nbsp;</li>
<li><a href="#method.detail">Method</a></li>
</ul>
</div>
<a name="skip.navbar.bottom">
<!--   -->
</a></div>
<!-- ======== END OF BOTTOM NAVBAR ======= -->
</body>
</html>
